"use client";

import React from 'react';
import SectionHeader from './shared/SectionHeader';
import { Sparkles } from 'lucide-react';

interface AiNarrativeSummaryProps {
  aiSummary: string;
  ticker: string;
  confidenceScore: number;
  currentRegime: string;
}

export default function AiNarrativeSummary({
  aiSummary,
  ticker,
  confidenceScore,
  currentRegime
}: AiNarrativeSummaryProps) {
  const cleanTicker = ticker.replace('.NS', '');

  // Split on double newlines for paragraph formatting
  const paragraphs = aiSummary
    ? aiSummary.split('\n\n').filter(p => p.trim().length > 0)
    : [];

  // Identify disclaimer paragraph (last one)
  const mainParagraphs = paragraphs.slice(0, -1);
  const disclaimerParagraph = paragraphs[paragraphs.length - 1] || '';

  return (
    <div className="bg-[#161B22] border border-[#21262D] p-5 hover:border-[#30363D] transition-all duration-200">
      <SectionHeader
        label="Section 9 — AI Narrative Summary"
        question={`What do all the signals say about ${cleanTicker}?`}
        accent="indigo"
      >
        <div className="flex items-center gap-1.5 text-xs text-[#6366F1] font-extrabold bg-[#6366F1]/10 border border-[#6366F1]/20 px-2 py-1">
          <Sparkles size={11} />
          AI Generated
        </div>
      </SectionHeader>

      {/* AI Policy Notice */}
      <div className="border border-[#21262D] bg-[#0D1117] px-4 py-2.5 mb-5 flex items-start gap-3">
        <span className="text-[#F59E0B] text-sm flex-shrink-0 mt-0.5">⚠</span>
        <p className="text-xs text-[#8B949E] leading-relaxed">
          <strong className="text-white">Educational Context Only.</strong> This summary is generated by an AI model based on the analytical measurements shown on this page.
          It does not contain investment advice, price targets, buy/sell recommendations, or forecasts of any kind.
          It is intended to help you understand what the current technical measurements collectively describe.
        </p>
      </div>

      {/* Context Tags */}
      <div className="flex flex-wrap items-center gap-2 mb-4">
        <span className="text-xs font-mono px-2 py-0.5 bg-[#0D1117] border border-[#21262D] text-[#8B949E] font-medium">
          REGIME: {currentRegime.toUpperCase()}
        </span>
        <span className="text-xs font-mono px-2 py-0.5 bg-[#0D1117] border border-[#21262D] text-[#8B949E] font-medium">
          CONFIDENCE: {confidenceScore}/100
        </span>
        <span className="text-xs font-mono px-2 py-0.5 bg-[#0D1117] border border-[#21262D] text-[#8B949E] font-medium">
          LLaMA 3.3 70B
        </span>
      </div>

      {/* Summary text */}
      {paragraphs.length > 0 ? (
        <div className="space-y-3">
          {mainParagraphs.map((para, idx) => (
            <p key={idx} className="text-sm text-white leading-relaxed font-normal">
              {para.trim()}
            </p>
          ))}

          {disclaimerParagraph && (
            <div className="border-t border-[#21262D] pt-3 mt-3">
              <p className="text-xs text-[#8B949E] leading-relaxed italic">
                {disclaimerParagraph.trim()}
              </p>
            </div>
          )}
        </div>
      ) : (
        <div className="bg-[#0D1117] border border-[#21262D] px-4 py-6 text-center">
          <p className="text-xs text-[#8B949E]">
            AI summary is being generated. Please refresh to see the narrative context.
          </p>
        </div>
      )}

      {/* Groq Attribution */}
      <div className="flex items-center gap-2 mt-5 pt-3 border-t border-[#21262D]">
        <span className="text-xs text-[#8B949E]">Powered by</span>
        <span className="text-xs font-mono font-bold text-[#6366F1]">Groq × LLaMA 3.3 70B</span>
        <span className="text-[#21262D]">·</span>
        <span className="text-xs text-[#8B949E]">Educational use only · No financial advice</span>
      </div>
    </div>
  );
}
